
title: "The Collegian Magazine"

# Deploy settings
# TODO: add the real domain
baseurl: "http://example.com"
languageCode: "en-us"

metaDataFormat: yaml
ignoreFiles:
  - \static/src/.*$
preserveTaxonomyNames: true
taxonomies:
  tag: tags
  category: categories
