
title: "The Collegian Magazine"

# Deploy settings
# TODO: add the real domain
baseurl: "http://dev-colmag.netlify.com"
languageCode: "en-us"

metaDataFormat: yaml
preserveTaxonomyNames: true
permalinks:
  article: /article/:year/:month/:slug/
  announcement: /announcement/:year/:month/:day/:slug/
  page: /:slug/
taxonomies:
  tag: tags
  category: categories
  author: authors
  issue: issues

menu:
  main:
    -
      name: "Articles"
      weight: 10
      url: "/article/"
    -
      name: "Staff"
      weight: 20
      url: "/staff/"
    -
      name: "Blog"
      weight: 30
      url: "/announcement/"
  footer:
    -
      name: "Articles"
      weight: 10
      url: "/article/"
    -
      name: "Staff"
      weight: 20
      url: "/staff/"
    -
      name: "Blog"
      weight: 30
      url: "/announcement/"


params:
  logo: '/logos/banner.svg'
