
title: "The Collegian Magazine"

# Deploy settings
# TODO: add the real domain
baseurl: "http://example.com"
languageCode: "en-us"

metaDataFormat: yaml
preserveTaxonomyNames: true
permalinks:
  article: /magazine/:year/:month/:slug/
  announcement: /announcements/:year/:month/:day/:slug/
taxonomies:
  tag: tags
  category: categories
  author: authors
  issue: issues
