
title: "The Collegian Magazine"

# Deploy settings
# TODO: add the real domain
baseurl: "http://dev-colmag.netlify.com"
languageCode: "en-us"

metaDataFormat: yaml
preserveTaxonomyNames: true
permalinks:
  article: /article/:year/:month/:slug/
  announcement: /announcement/:year/:month/:day/:slug/
  page: /:slug/
taxonomies:
  tag: tags
  category: categories
  author: authors
  issue: issues

menu:
  main:
    -
      name: "Articles"
      weight: 10
      url: "/article/"
    -
      name: "Staff"
      weight: 20
      url: "/staff/"
    -
      name: "Blog"
      weight: 30
      url: "/announcement/"
  footer:
    -
      name: "Home"
      weight: -10
      url: "/"
    -
      name: "Articles"
      weight: 10
      url: "/article/"
    -
      name: "Staff"
      weight: 20
      url: "/staff/"
    -
      name: "Blog"
      weight: 30
      url: "/announcement/"


params:
  site_name: The Collegian Magazine
  description: The Collegian Magazine combines long-form investigative journalism and a sleek aesthetic in creating a biannual, award-winning, student-led publication.
  tagline: Documenting the curious in Gambier, Ohio.
  logo: '/logos/banner.svg'
  email: 'thecollegianmagazine@kenyon.edu'
